export default {
    head: {
        left: {
            x: 0,
            y: 48,
            w: 8,
            h: 8,
            flipY: true,
        },
        front: {
            x: 8,
            y: 48,
            w: 8,
            h: 8,
        },
        right: {
            x: 16,
            y: 48,
            w: 8,
            h: 8,
            flipY: true,
        },
        back: {
            x: 24,
            y: 48,
            w: 8,
            h: 8,
        },
        top: {
            x: 8,
            y: 56,
            w: 8,
            h: 8,
        },
        bottom: {
            x: 16,
            y: 56,
            w: 8,
            h: 8,
            flipX: true,
            flipY: true,
        },
    },
    body: {
        left: {
            x: 16,
            y: 32,
            w: 4,
            h: 12,
        },
        front: {
            x: 20,
            y: 32,
            w: 8,
            h: 12,
        },
        right: {
            x: 28,
            y: 32,
            w: 4,
            h: 12,
        },
        back: {
            x: 32,
            y: 32,
            w: 8,
            h: 12,
        },
        top: {
            x: 20,
            y: 44,
            w: 8,
            h: 4,
            flipY: true,
        },
        bottom: {
            x: 28,
            y: 44,
            w: 8,
            h: 4,
        },
    },
    rightArm: {
        left: {
            x: 32,
            y: 0,
            w: 4,
            h: 12,
            flipY: true,
        },
        front: {
            x: 36,
            y: 0,
            w: 4,
            h: 12,
            sw: 3,
            flipY: true,
        },
        right: {
            x: 40,
            y: 0,
            w: 4,
            h: 12,
            sx: 39,
            flipY: true,
        },
        back: {
            x: 44,
            y: 0,
            w: 4,
            h: 12,
            sx: 43,
            sw: 3,
            flipY: true,
        },
        top: {
            x: 36,
            y: 12,
            w: 4,
            h: 4,
            sw: 3,
            flipX: false,
        },
        bottom: {
            x: 40,
            y: 12,
            w: 4,
            h: 4,
            sx: 39,
            sw: 3,
            flipY: true,
            flipX: true,
        },
    },
    leftArm: {
        left: {
            x: 40,
            y: 32,
            w: 4,
            h: 12,
            flipY: true,
        },
        front: {
            x: 44,
            y: 32,
            w: 4,
            h: 12,
            sw: 3,
            flipY: true,
        },
        right: {
            x: 48,
            y: 32,
            w: 4,
            h: 12,
            sx: 47,
            flipY: true,
        },
        back: {
            x: 52,
            y: 32,
            w: 4,
            h: 12,
            sx: 51,
            sw: 3,
            flipY: true,
        },
        top: {
            x: 44,
            y: 44,
            w: 4,
            h: 4,
            sw: 3,
            flipX: false,
        },
        bottom: {
            x: 48,
            y: 44,
            w: 4,
            h: 4,
            sx: 47,
            sw: 3,
            flipY: true,
            flipX: true,
        },
    },
    rightLeg: {
        left: {
            x: 16,
            y: 0,
            w: 4,
            h: 12,
            flipY: true,
        },
        front: {
            x: 20,
            y: 0,
            w: 4,
            h: 12,
            flipY: true,
        },
        right: {
            x: 24,
            y: 0,
            w: 4,
            h: 12,
            flipY: true,
        },
        back: {
            x: 28,
            y: 0,
            w: 4,
            h: 12,
            flipY: true,
        },
        top: {
            x: 20,
            y: 12,
            w: 4,
            h: 4,
            flipX: false,
        },
        bottom: {
            x: 24,
            y: 12,
            w: 4,
            h: 4,
            flipX: true,
        },
    },
    leftLeg: {
        left: {
            x: 0,
            y: 32,
            w: 4,
            h: 12,
            flipY: true,
        },
        front: {
            x: 4,
            y: 32,
            w: 4,
            h: 12,
            flipY: true,
        },
        right: {
            x: 8,
            y: 32,
            w: 4,
            h: 12,
            flipY: true,
        },
        back: {
            x: 12,
            y: 32,
            w: 4,
            h: 12,
            flipY: true,
        },
        top: {
            x: 4,
            y: 44,
            w: 4,
            h: 4,
            flipX: false,
        },
        bottom: {
            x: 8,
            y: 44,
            w: 4,
            h: 4,
            flipX: true,
        },
    },
    hat: {
        left: {
            x: 32,
            y: 48,
            w: 8,
            h: 8,
            flipY: true,
        },
        front: {
            x: 40,
            y: 48,
            w: 8,
            h: 8,
        },
        right: {
            x: 48,
            y: 48,
            w: 8,
            h: 8,
            flipY: true,
        },
        back: {
            x: 56,
            y: 48,
            w: 8,
            h: 8,
        },
        top: {
            x: 40,
            y: 56,
            w: 8,
            h: 8,
            flipY: true,
        },
        bottom: {
            x: 48,
            y: 56,
            w: 8,
            h: 8,
            flipY: true,
            flipX: true,
        },
    },
    jacket: {
        left: {
            x: 16,
            y: 16,
            w: 4,
            h: 12,
            flipY: true,
        },
        front: {
            x: 20,
            y: 16,
            w: 8,
            h: 12,
        },
        right: {
            x: 28,
            y: 16,
            w: 4,
            h: 12,
            flipY: true,
        },
        back: {
            x: 32,
            y: 16,
            w: 8,
            h: 12,
        },
        top: {
            x: 20,
            y: 28,
            w: 8,
            h: 4,
        },
        bottom: {
            x: 28,
            y: 28,
            w: 8,
            h: 4,
            flipY: true,
            flipX: true,
        },
    },
    rightSleeve: {
        left: {
            x: 48,
            y: 0,
            w: 4,
            h: 12,
        },
        front: {
            x: 52,
            y: 0,
            w: 4,
            h: 12,
            sw: 3,
        },
        right: {
            x: 56,
            y: 0,
            w: 4,
            h: 12,
            sx: 55,
        },
        back: {
            x: 60,
            y: 0,
            w: 4,
            h: 12,
            sx: 59,
            sw: 3,
        },
        top: {
            x: 52,
            y: 12,
            w: 4,
            h: 4,
            sw: 3,
        },
        bottom: {
            x: 56,
            y: 12,
            w: 4,
            h: 4,
            sx: 55,
            sw: 3,
            flipY: true,
            flipX: true,
        },
    },
    leftSleeve: {
        left: {
            x: 40,
            y: 16,
            w: 4,
            h: 12,
        },
        front: {
            x: 44,
            y: 16,
            w: 4,
            h: 12,
            sw: 3,
        },
        right: {
            x: 48,
            y: 16,
            w: 4,
            h: 12,
            sx: 47,
        },
        back: {
            x: 52,
            y: 16,
            w: 4,
            h: 12,
            sx: 51,
            sw: 3,
        },
        top: {
            x: 44,
            y: 28,
            w: 4,
            h: 4,
            sw: 3,
        },
        bottom: {
            x: 48,
            y: 28,
            w: 4,
            h: 4,
            sx: 47,
            sw: 3,
            flipY: true,
            flipX: true,
        },
    },
    rightTrousers: {
        left: {
            x: 0,
            y: 0,
            w: 4,
            h: 12,
            flipY: true,
        },
        front: {
            x: 4,
            y: 0,
            w: 4,
            h: 12,
            flipY: true,
        },
        right: {
            x: 8,
            y: 0,
            w: 4,
            h: 12,
            flipY: true,
        },
        back: {
            x: 12,
            y: 0,
            w: 4,
            h: 12,
            flipY: true,
        },
        top: {
            x: 4,
            y: 12,
            w: 4,
            h: 4,
        },
        bottom: {
            x: 8,
            y: 12,
            w: 4,
            h: 4,
            flipX: true,
        },
    },
    leftTrousers: {
        left: {
            x: 0,
            y: 16,
            w: 4,
            h: 12,
            flipY: true,
        },
        front: {
            x: 4,
            y: 16,
            w: 4,
            h: 12,
            flipY: true,
        },
        right: {
            x: 8,
            y: 16,
            w: 4,
            h: 12,
            flipY: true,
        },
        back: {
            x: 12,
            y: 16,
            w: 4,
            h: 12,
            flipY: true,
        },
        top: {
            x: 4,
            y: 28,
            w: 4,
            h: 4,
        },
        bottom: {
            x: 8,
            y: 28,
            w: 4,
            h: 4,
            flipX: true,
        },
    },
};
